### ISSUE TITLE
issues in cora dataset

### ISSUE THREAD

**Issue by snash4** [xhuang31/AANE_Python#2]
Hi, 
 Thanks for the code. 
I tried your code on standard cora dataset. It gives me very poor results. 
I could not understand the possible reasons. Could you provide some input.

**Comment by xhuang31** [comment]
AANE is designed for large-scale attributed networks. It works very well on citation networks. You could try the one on http://people.tamu.edu/~xhuang/Code.html. The results are shown in paper "Large-Scale Heterogeneous Feature Embedding," AAAI, 2019. 

For the Cora with 2708 nodes, AANE performs well on the pure network, and bad on the attributed network. It might because the node attributes only have 717 dimensions after removing the zeros. 

Thus, Cora might be too small for AANE. There are also some papers applied AANE to Cora, such as http://www.mlgworkshop.org/2018/papers/MLG2018_paper_6.pdf and https://arxiv.org/pdf/1811.07609.pdf

Thanks.

**Comment by xhuang31** [comment]
May be we need some regularization terms for small datasets.
